# Generated by Django 3.2 on 2025-04-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20250414_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link_token',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Токен короткой ссылки'),
        ),
        migrations.DeleteModel(
            name='ShortLink',
        ),
    ]
