# Generated by Django 3.2 on 2025-04-13 21:44

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.expressions
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userdetail_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), users.validators.validate_forbidden_username], verbose_name='Имя пользователя'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('author')), name='not_self_following'),
        ),
    ]
